<template>
  <div>
    <div v-for="(item, index) in list" :key="index">
      <h3>{{ item.series }}</h3>
      <table class="color-table" @click="pickColor">
        <thead>
          <tr>
            <th>Name</th>
            <th>Romanized</th>
            <th>English translation</th>
            <th>RGB</th>
            <th>HEX</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(color, i) in item.data" :key="i">
            <td>{{ color.name }}</td>
            <td>{{ color.romanized }}</td>
            <td>{{ color.en }}</td>
            <td
              :style="{ background: color.hex }"
              :data-value="'rgb(' + color.rgb + ')'"
            >
              {{ color.rgb }}
            </td>
            <td :style="{ background: color.hex }" :data-value="color.hex">
              {{ color.hex }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { BugMessage } from '../src/index';

export default defineComponent({
  setup() {
    const list = ref([
      {
        series: 'Red/violet series',
        data: [
          {
            name: '一斤染',
            romanized: 'Ikkonzome',
            en: 'One kin (0.6 kg (1.3 lb)) dye',
            rgb: '240,143,144',
            hex: '#F08F90',
          },
          {
            name: '桃色',
            romanized: 'Momo-iro',
            en: 'Peach-colored',
            rgb: '244,121,131',
            hex: '#F47983',
          },
          {
            name: '紅梅色',
            romanized: 'Kōbai-iro',
            en: 'Red plum colored',
            rgb: '219,90,107',
            hex: '#DB5A6B',
          },
          {
            name: '中紅',
            romanized: 'Nakabeni',
            en: 'Medium crimson (dye)',
            rgb: '201,55,86',
            hex: '#C93756',
          },
          {
            name: '桜色',
            romanized: 'Sakura-iro',
            en: 'Cherry blossom color',
            rgb: '252,201,185',
            hex: '#FCC9B9',
          },
          {
            name: '退紅',
            romanized: 'Arazome',
            en: 'Washed-out crimson (dye)',
            rgb: '255,179,167',
            hex: '#FFB3A7',
          },
          {
            name: '薄紅',
            romanized: 'Usubeni',
            en: 'Pale crimson (dye)',
            rgb: '242,102,108',
            hex: '#F2666C',
          },
        ],
      },
      {
        series: 'Red series',
        data: [
          {
            name: '鴇羽色',
            romanized: 'Tokiha-iro',
            en: 'Ibis wing color',
            rgb: '245,143,132',
            hex: '#F58F84',
          },
          {
            name: '桜鼠',
            romanized: 'Sakuranezumi',
            en: 'Cherry blossom mouse grey',
            rgb: '172,129,118',
            hex: '#AC8181',
          },
          {
            name: '長春色',
            romanized: 'Chōshun-iro',
            en: 'Long spring (season) color',
            rgb: '185,87,84',
            hex: '#B95754',
          },
          {
            name: '唐紅/韓紅',
            romanized: 'Karakurenai',
            en: 'Foreign crimson[a]',
            rgb: '201,31,55',
            hex: '#C91F37',
          },
          {
            name: '臙脂色',
            romanized: 'Enji-iro',
            en: 'Cochineal red/rouge',
            rgb: '157,41,51',
            hex: '#9D2933',
          },
          {
            name: '深緋',
            romanized: 'Kokiake',
            en: 'Deep scarlet',
            rgb: '123,59,58',
            hex: '#7B3B3A',
          },
          {
            name: '甚三紅',
            romanized: 'Jinzamomi',
            en: 'Thrice-dyed crimson',
            rgb: '247,102,90',
            hex: '#F7665A',
          },
          {
            name: '水がき',
            romanized: 'Mizugaki',
            en: 'Water persimmon',
            rgb: '181,108,96',
            hex: '#B56C60',
          },
          {
            name: '梅鼠',
            romanized: 'Umenezumi',
            en: 'Plum-blossom mouse grey',
            rgb: '151,100,90',
            hex: '#97645A',
          },
          {
            name: '蘇芳香',
            romanized: "Su'ōkō",
            en: 'Sappanwood incense',
            rgb: '162,79,70',
            hex: '#A24F46',
          },
          {
            name: '赤紅',
            romanized: 'Akabeni',
            en: 'Pure crimson (dye)',
            rgb: '195,39,43',
            hex: '#C3272B',
          },
          {
            name: '真朱',
            romanized: 'Shinshu',
            en: 'True red',
            rgb: '143,29,33',
            hex: '#8F1D21',
          },
          {
            name: '小豆色',
            romanized: 'Azuki-iro',
            en: 'Azuki bean color',
            rgb: '103,36,34',
            hex: '#672422',
          },
          {
            name: '銀朱',
            romanized: 'Ginshu',
            en: 'Greyed red (lit. silvered red)',
            rgb: '188,45,41',
            hex: '#BC2D29',
          },
          {
            name: '海老茶',
            romanized: 'Ebicha',
            en: 'Maroon (shrimp brown)',
            rgb: '94,40,36',
            hex: '#5E2824',
          },
          {
            name: '栗梅',
            romanized: 'Kiriume',
            en: 'Red-brown (lit. chestnut-plum)',
            rgb: '139,53,45',
            hex: '#8B352D',
          },
          {
            name: '曙色',
            romanized: 'Akebono-iro',
            en: 'Dawn-color',
            rgb: '250,123,98',
            hex: '#FA7B62',
          },
          {
            name: '珊瑚色',
            romanized: 'Sango-iro',
            en: 'Coral color',
            rgb: '248,103,79',
            hex: '#F8674F',
          },
          {
            name: '猩々緋',
            romanized: 'Shōjōhi',
            en: 'Red-orange (lit. orangutan-colored)',
            rgb: '220,48,35',
            hex: '#DC3023',
          },
          {
            name: '芝翫茶',
            romanized: 'Shikancha',
            en: 'Wilted brown (lit. wilted lawn-clippings)',
            rgb: '171,76,61',
            hex: '#AB4C3D',
          },
          {
            name: '柿渋色',
            romanized: 'Kakishibu-iro',
            en: 'Persimmon-juice color',
            rgb: '147,67,55',
            hex: '#934337',
          },
          {
            name: '紅樺',
            romanized: 'Benikaba',
            en: 'Red birch',
            rgb: '157,43,34',
            hex: '#9D2B22',
          },
          {
            name: '紅鳶',
            romanized: 'Benitobi',
            en: 'Red kite (bird species)',
            rgb: '145,50,40',
            hex: '#913228',
          },
          {
            name: '紅檜皮',
            romanized: 'Benihibata',
            en: 'Cypress bark red',
            rgb: '111,48,40',
            hex: '#6F3028',
          },
          {
            name: '黒鳶',
            romanized: 'Kurotobi',
            en: 'Black kite (bird species)',
            rgb: '53,30,28',
            hex: '#351E1C',
          },
          {
            name: '紅緋',
            romanized: 'Benihi',
            en: 'Blood red',
            rgb: '243,83,54',
            hex: '#F35336',
          },
          {
            name: '照柿',
            romanized: 'Terigaki',
            en: 'Glazed persimmon',
            rgb: '211,78,54',
            hex: '#D34E36',
          },
          {
            name: '緋',
            romanized: 'Ake',
            en: 'Scarlet (blood)',
            rgb: '207,58,36',
            hex: '#CF3A24',
          },
          {
            name: '江戸茶',
            romanized: 'Edocha',
            en: 'Red-brown (Edo brown)',
            rgb: '161,61,45',
            hex: '#A13D2D',
          },
          {
            name: '紅柄色',
            romanized: 'Bengara-iro',
            en: 'Dyestalk red (lit. the color from dying with the stalk of the beni (safflower) plant)',
            rgb: '145,50,37',
            hex: '#913225',
          },
          {
            name: '檜皮色',
            romanized: 'Hihada-iro',
            en: 'Cypress bark color',
            rgb: '117,46,35',
            hex: '#752E23',
          },
          {
            name: '宍色',
            romanized: 'Shishi-iro',
            en: 'Meat-color',
            rgb: '249,144,111',
            hex: '#F9906F',
          },
          {
            name: '洗朱',
            romanized: 'Araishu',
            en: 'Rinsed-out red',
            rgb: '255,121,82',
            hex: '#FF7952',
          },
          {
            name: '赤香色',
            romanized: 'Akakō-iro',
            en: 'Red incense-colored',
            rgb: '240,127,94',
            hex: '#F07F5E',
          },
          {
            name: 'ときがら茶',
            romanized: 'Tokigaracha',
            en: 'Brewed mustard-brown',
            rgb: '230,131,100',
            hex: '#E68364',
          },
          {
            name: '黄丹',
            romanized: 'Ōtan',
            en: 'Ochre (earthen yellow-red-brown)',
            rgb: '255,78,32',
            hex: '#FF4E20',
          },
          {
            name: '蘇比',
            romanized: 'Sohi',
            en: 'Overdyed/refreshed red-brown',
            rgb: '227,92,56',
            hex: '#E35C38',
          },
          {
            name: '遠州茶',
            romanized: 'Enshūcha',
            en: 'Muddy brown (lit. the brown of a distant river)',
            rgb: '203,102,73',
            hex: '#CB6649',
          },
          {
            name: '唐茶',
            romanized: 'Karacha',
            en: 'Spicy red-brown (Chinese tea brown)',
            rgb: '179,92,68',
            hex: '#B35C44',
          },
          {
            name: '樺茶',
            romanized: 'Kabacha',
            en: 'Birch brown',
            rgb: '177,74,48',
            hex: '#B14A30',
          },
          {
            name: '宗傳唐茶',
            romanized: 'Sōdenkaracha',
            en: 'Faded spicy red-brown',
            rgb: '155,83,63',
            hex: '#9B533F',
          },
          {
            name: '雀茶',
            romanized: 'Suzumecha',
            en: 'Sparrow-brown',
            rgb: '140,71,54',
            hex: '#8C4736',
          },
          {
            name: '栗皮茶',
            romanized: 'Kurikawacha',
            en: 'Chestnut-leather brown',
            rgb: '96,40,30',
            hex: '#60281E',
          },
          {
            name: '百塩茶',
            romanized: 'Momoshiocha',
            en: 'Boiled red bean brown',
            rgb: '84,45,36',
            hex: '#542D24',
          },
          {
            name: '鳶色',
            romanized: 'Tobi-iro',
            en: 'Ibis-color',
            rgb: '76,34,27',
            hex: '#4C221B',
          },
          {
            name: '朱色',
            romanized: 'Shu-iro',
            en: 'Cinnabar-color',
            rgb: '255,53,0',
            hex: '#ff3500',
          },
        ],
      },
      {
        series: 'Yellow/red series',
        data: [
          {
            name: '胡桃染',
            romanized: 'Kurumizome',
            en: 'Walnut-dyed',
            rgb: '159,116,98',
            hex: '#9F7462',
          },
          {
            name: '蒲色',
            romanized: 'Kaba-iro',
            en: 'Cattail color',
            rgb: '182,73,37',
            hex: '#B64925',
          },
          {
            name: '黄櫨染',
            romanized: 'Kōrozen',
            en: 'Sumac-dyed',
            rgb: '89,43,31',
            hex: '#592B1F',
          },
          {
            name: '焦茶',
            romanized: 'Kogecha',
            en: 'Scorched brown',
            rgb: '53,31,25',
            hex: '#351F19',
          },
          {
            name: '深支子',
            romanized: 'Kokikuchinashi',
            en: 'Rich gardenia',
            rgb: '245,127,79',
            hex: '#F57F4F',
          },
          {
            name: '洗柿',
            romanized: 'Araigaki',
            en: 'Washed-out persimmon',
            rgb: '236,130,84',
            hex: '#EC8254',
          },
          {
            name: '代赭色',
            romanized: 'Taisha-iro',
            en: 'Red ochre color',
            rgb: '159,82,51',
            hex: '#9F5233',
          },
          {
            name: '赤白橡',
            romanized: 'Akashirotsurubami',
            en: 'Sawtooth oak',
            rgb: '236,149,108',
            hex: '#EC956C',
          },
          {
            name: '礪茶',
            romanized: 'Tonocha',
            en: 'Polished brown',
            rgb: '152,85,56',
            hex: '#985538',
          },
          {
            name: '煎茶色',
            romanized: 'Sencha-iro',
            en: 'Green tea-colored',
            rgb: '130,75,53',
            hex: '#824B35',
          },
          {
            name: '洒落柿',
            romanized: 'Sharegaki',
            en: 'Stylish persimmon',
            rgb: '255,162,107',
            hex: '#FFA26B',
          },
          {
            name: '薄柿',
            romanized: 'Usugaki',
            en: 'Pale persimmon',
            rgb: '252,164,116',
            hex: '#FCA474',
          },
          {
            name: '萱草色',
            romanized: 'Kanzō-iro',
            en: 'Daylily-colored',
            rgb: '255,137,54',
            hex: '#FF8936',
          },
          {
            name: '梅染',
            romanized: 'Umezome',
            en: 'Plum-dyed',
            rgb: '250,146,88',
            hex: '#FA9258',
          },
          {
            name: '紅鬱金',
            romanized: "Beni'ukon",
            en: 'Red-bronze (lit. red dye and turmeric)',
            rgb: '251,129,54',
            hex: '#FB8136',
          },
          {
            name: '丁子茶',
            romanized: 'Chōjicha',
            en: 'Clove-brown',
            rgb: '143,88,60',
            hex: '#8F583C',
          },
          {
            name: '憲法染',
            romanized: 'Kenpōzome',
            en: 'Legal dye (from when color use was regulated by class)',
            rgb: '46,33,27',
            hex: '#2E211B',
          },
          {
            name: '枇杷茶',
            romanized: 'Biwacha',
            en: 'Loquat tree-brown',
            rgb: '171,97,52',
            hex: '#AB6134',
          },
          {
            name: '琥珀色',
            romanized: 'Kohaku-iro',
            en: 'Amber color',
            rgb: '202,105,36',
            hex: '#CA6924',
          },
          {
            name: '淡香',
            romanized: 'Usukō',
            en: 'Pale incense',
            rgb: '255,165,101',
            hex: '#FFA565',
          },
          {
            name: '朽葉色',
            romanized: 'Kuchiba-iro',
            en: 'Decaying leaves color',
            rgb: '213,120,53',
            hex: '#D57835',
          },
          {
            name: '金茶',
            romanized: 'Kincha',
            en: 'Golden brown',
            rgb: '198,107,39',
            hex: '#C66B27',
          },
          {
            name: '丁子染',
            romanized: 'Chōjizome',
            en: 'Clove-dyed',
            rgb: '169,98,50',
            hex: '#A96232',
          },
          {
            name: '狐色',
            romanized: 'Kitsune-iro',
            en: 'Fox-color',
            rgb: '152,86,41',
            hex: '#985629',
          },
          {
            name: '柴染',
            romanized: 'Fushizome',
            en: 'Brushwood-dyed',
            rgb: '140,89,57',
            hex: '#8C5939',
          },
          {
            name: '伽羅色',
            romanized: 'Kyara-iro',
            en: 'Aloewood-color',
            rgb: '106,67,45',
            hex: '#6A432D',
          },
          {
            name: '煤竹色',
            romanized: 'Susutake-iro',
            en: 'Weathered bamboo (lit. "sooty")',
            rgb: '89,58,39',
            hex: '#593A27',
          },
          {
            name: '白茶',
            romanized: 'Shiracha',
            en: 'White tea-colored',
            rgb: '196,142,105',
            hex: '#C48E69',
          },
          {
            name: '黄土色',
            romanized: 'Ōdo-iro',
            en: 'Ochre (lit. earthen yellow)',
            rgb: '190,127,81',
            hex: '#BE7F51',
          },
          {
            name: '銀煤竹',
            romanized: 'Kinsusutake',
            en: 'Golden-grey bamboo (dried and weathered)',
            rgb: '125,78,45',
            hex: '#7D4E2D',
          },
          {
            name: '黄唐茶',
            romanized: 'Kigaracha',
            en: 'Chinese yellow tea-colored',
            rgb: '183,112,45',
            hex: '#B7702D',
          },
          {
            name: '媚茶',
            romanized: 'Kobicha',
            en: 'Kobi tea',
            rgb: '107,68,35',
            hex: '#6B4423',
          },
          {
            name: '赤朽葉',
            romanized: 'Akakuchiba',
            en: 'Red fallen leaves',
            rgb: '219,132,73',
            hex: '#DB8449',
          },
        ],
      },
      {
        series: 'Yellow series',
        data: [
          {
            name: '浅黄',
            romanized: 'Asagi',
            en: 'Light yellow',
            rgb: '247,187,125',
            hex: '#F7BB7D',
          },
          {
            name: '山吹色',
            romanized: 'Yamabuki-iro',
            en: 'Golden yellow (a particular variety of rose)',
            rgb: '255,164,0',
            hex: '#FFA400',
          },
          {
            name: '玉子色',
            romanized: 'Tamago-iro',
            en: 'Egg-colored',
            rgb: '255,166,49',
            hex: '#FFA631',
          },
          {
            name: '櫨染',
            romanized: 'Hajizome',
            en: 'Sumac-dyed',
            rgb: '224,138,30',
            hex: '#E08A1E',
          },
          {
            name: '山吹茶',
            romanized: 'Yamabukicha',
            en: 'Gold-brown',
            rgb: '203,126,31',
            hex: '#CB7E1F',
          },
          {
            name: '桑染',
            romanized: 'Kuwazome',
            en: 'Mulberry-dyed',
            rgb: '197,127,46',
            hex: '#C57F2E',
          },
          {
            name: '生壁色',
            romanized: 'Namakabe-iro',
            en: 'The color of undried plaster',
            rgb: '120,94,73',
            hex: '#785E49',
          },
          {
            name: '梔子',
            romanized: 'Kuchinashi',
            en: 'Cape jasmine or gardenia',
            rgb: '255,185,90',
            hex: '#FFB95A',
          },
          {
            name: '玉蜀黍色',
            romanized: 'Tōmorokoshi-iro',
            en: 'Corn-colored',
            rgb: '250,169,69',
            hex: '#FAA945',
          },
          {
            name: '白橡',
            romanized: 'Shirotsurubami',
            en: 'White oak',
            rgb: '206,159,111',
            hex: '#CE9F6F',
          },
          {
            name: '黄橡',
            romanized: 'Kitsurubami',
            en: 'Golden oak',
            rgb: '187,129,65',
            hex: '#BB8141',
          },
          {
            name: '藤黄',
            romanized: "Tō'ō",
            en: 'Gamboge',
            rgb: '255,182,30',
            hex: '#FFB61E',
          },
          {
            name: '花葉色',
            romanized: 'Hanaba-iro or kayou-iro',
            en: 'Floral leaf-colored',
            rgb: '255,185,78',
            hex: '#FFB94E',
          },
          {
            name: '鳥の子色',
            romanized: 'Torinoko-iro',
            en: 'Eggshell paper-colored',
            rgb: '226,190,159',
            hex: '#E2BE9F',
          },
          {
            name: '鬱金色',
            romanized: 'Ukon-iro',
            en: 'Turmeric-colored',
            rgb: '230,155,58',
            hex: '#E69B3A',
          },
          {
            name: '黄朽葉',
            romanized: 'Kikuchiba',
            en: 'Golden fallen leaves',
            rgb: '226,156,69',
            hex: '#E29C45',
          },
          {
            name: '利休白茶',
            romanized: 'Rikyūshiracha',
            en: "Faded Sen no Rikyū's tea",
            rgb: '176,146,122',
            hex: '#B0927A',
          },
          {
            name: '利休茶',
            romanized: 'Rikyūcha',
            en: "Sen no Rikyū's tea",
            rgb: '130,107,88',
            hex: '#826B58',
          },
          {
            name: '灰汁色',
            romanized: 'Aku-iro',
            en: 'Lye-colored',
            rgb: '127,107,93',
            hex: '#7F6B5D',
          },
          {
            name: '肥後煤竹',
            romanized: 'Higosusutake',
            en: 'Japanese iris and sooty bamboo',
            rgb: '127,93,59',
            hex: '#7F5D3B',
          },
          {
            name: '路考茶',
            romanized: 'Rokōcha',
            en: 'Contemplation in a tea garden',
            rgb: '102,83,67',
            hex: '#665343',
          },
          {
            name: '海松茶',
            romanized: 'Mirucha',
            en: 'Simmered seaweed',
            rgb: '76,61,48',
            hex: '#4C3D30',
          },
          {
            name: '菜種油色',
            romanized: 'Nataneyu-iro',
            en: 'Rapeseed oil-colored',
            rgb: '161,121,23',
            hex: '#A17917',
          },
          {
            name: '黄海松茶',
            romanized: 'Kimirucha',
            en: 'Yellow Sea pine-brown',
            rgb: '137,108,57',
            hex: '#896C39',
          },
          {
            name: '鶯茶',
            romanized: 'Uguisucha',
            en: 'Nightingale-brown (greenish brown)',
            rgb: '92,72,39',
            hex: '#5C4827',
          },
          {
            name: '菜の花色',
            romanized: 'Nanohanacha',
            en: 'Rape-blossom brown',
            rgb: '227,177,48',
            hex: '#E3B130',
          },
          {
            name: '苅萱',
            romanized: 'Kariyasu',
            en: 'Japanese triandra grass (Themeda japonica)',
            rgb: '226,177,60',
            hex: '#E2B13C',
          },
          {
            name: '黄蘗',
            romanized: 'Kihada',
            en: 'Amur cork tree (Phellodendron amurense)',
            rgb: '243,193,58',
            hex: '#F3C13A',
          },
          {
            name: '蒸栗色',
            romanized: 'Mushikuri-iro',
            en: 'Steamed chestnut color',
            rgb: '211,177,125',
            hex: '#D3B17D',
          },
          {
            name: '青朽葉',
            romanized: 'Aokuchiba',
            en: 'Pale fallen leaves',
            rgb: '170,135,54',
            hex: '#AA8736',
          },
          {
            name: '鶸茶',
            romanized: 'Hiwacha',
            en: 'Finch-brown (Cardueline finch)',
            rgb: '149,123,56',
            hex: '#957B38',
          },
          {
            name: '女郎花',
            romanized: 'Ominaeshi',
            en: 'Patrinia flowers (Patrinia scabiosaefolia)',
            rgb: '217,182,17',
            hex: '#D9B611',
          },
          {
            name: '鶯色',
            romanized: 'Uguisu-iro',
            en: 'Nightingale-colored',
            rgb: '100,85,48',
            hex: '#645530',
          },
        ],
      },
      {
        series: 'Yellow/green series',
        data: [
          {
            name: '鶸色',
            romanized: 'Hiwa-iro',
            en: 'Greenfinch color',
            rgb: '189,169,40',
            hex: '#BDA928',
          },
          {
            name: '青白橡',
            romanized: 'Aoshirotsurubami',
            en: 'Pale oak',
            rgb: '187,164,109',
            hex: '#BBA46D',
          },
          {
            name: '柳茶',
            romanized: 'Yanagicha',
            en: 'Willow tea',
            rgb: '156,138,77',
            hex: '#9C8A4D',
          },
          {
            name: '璃寛茶',
            romanized: 'Rikancha',
            en: 'Rikan brown',
            rgb: '83,74,50',
            hex: '#534A32',
          },
          {
            name: '藍媚茶',
            romanized: 'Aikobicha',
            en: 'Indigo tea',
            rgb: '71,63,45',
            hex: '#473F2D',
          },
          {
            name: '苔色',
            romanized: 'Koke-iro',
            en: 'Moss color',
            rgb: '139,125,58',
            hex: '#8B7D3A',
          },
          {
            name: '海松色',
            romanized: 'Miru-iro',
            en: 'Codium fragile seaweed color',
            rgb: '82,75,42',
            hex: '#524B2A',
          },
          {
            name: '千歳茶',
            romanized: 'Sensaicha',
            en: 'Thousand year old brown',
            rgb: '59,52,41',
            hex: '#3B3429',
          },
          {
            name: '梅幸茶',
            romanized: 'Baikōcha',
            en: 'Baiko brown',
            rgb: '133,124,85',
            hex: '#857C55',
          },
          {
            name: '岩井茶',
            romanized: 'Iwaicha',
            en: 'Iwai brown[2]',
            rgb: '94,85,69',
            hex: '#5E5545',
          },
          {
            name: '鶸萌黄',
            romanized: "Hiwamo'egi",
            en: 'Siskin sprout yellow',
            rgb: '122,148,46',
            hex: '#7A942E',
          },
          {
            name: '柳煤竹',
            romanized: 'Yanagisusutake',
            en: 'Sooty willow bamboo',
            rgb: '77,75,58',
            hex: '#4D4B3A',
          },
          {
            name: '裏柳',
            romanized: 'Urahayanagi',
            en: 'Underside of willow leaves',
            rgb: '188,181,140',
            hex: '#BCB58C',
          },
          {
            name: '淡萌黄',
            romanized: "Usumo'egi",
            en: 'Pale young green onion',
            rgb: '141,178,85',
            hex: '#8DB255',
          },
          {
            name: '柳染',
            romanized: 'Yanagizome',
            en: 'Willow-dyed',
            rgb: '140,158,94',
            hex: '#8C9E5E',
          },
          {
            name: '萌黄',
            romanized: "Mo'egi",
            en: 'Fresh onion',
            rgb: '91,137,48',
            hex: '#5B8930',
          },
          {
            name: '青丹',
            romanized: 'Aoni',
            en: 'Blue-black clay[3]',
            rgb: '82,89,59',
            hex: '#52593B',
          },
          {
            name: '松葉色',
            romanized: 'Matsuba-iro',
            en: 'Pine needle color',
            rgb: '69,77,50',
            hex: '#454D32',
          },
        ],
      },
      {
        series: 'Green/blue green series',
        data: [
          {
            name: '薄青',
            romanized: "Usu'ao",
            en: 'Pale blue',
            rgb: '140,156,118',
            hex: '#8C9C76',
          },
          {
            name: '若竹色',
            romanized: 'Wakatake-iro',
            en: 'Young bamboo color',
            rgb: '107,147,98',
            hex: '#6B9362',
          },
          {
            name: '柳鼠',
            romanized: 'Yanaginezumi',
            en: 'Willow grey',
            rgb: '129,123,105',
            hex: '#817B69',
          },
          {
            name: '老竹色',
            romanized: 'Oitake-iro',
            en: 'Old bamboo color',
            rgb: '94,100,79',
            hex: '#5E644F',
          },
          {
            name: '千歳緑',
            romanized: 'Chitosemidori',
            en: 'Thousand year old green',
            rgb: '55,66,49',
            hex: '#374231',
          },
          {
            name: '緑',
            romanized: 'Midori',
            en: 'Green',
            rgb: '42,96,59',
            hex: '#2A603B',
          },
          {
            name: '白緑',
            romanized: 'Byakuroku',
            en: 'Whitish green',
            rgb: '165,186,147',
            hex: '#A5BA93',
          },
          {
            name: '錆青磁',
            romanized: 'Sabiseiji',
            en: 'Rusty celadon',
            rgb: '137,138,116',
            hex: '#898A74',
          },
          {
            name: '緑青',
            romanized: 'Rokushō',
            en: 'Patina',
            rgb: '64,122,82',
            hex: '#407A52',
          },
          {
            name: '木賊色',
            romanized: 'Tokusa-iro',
            en: 'Horsetail color',
            rgb: '61,93,66',
            hex: '#3D5D42',
          },
          {
            name: '御納戸茶',
            romanized: 'Onandocha',
            en: 'Storeroom brown',
            rgb: '61,64,53',
            hex: '#3D4035',
          },
          {
            name: '青竹色',
            romanized: 'Aotake-iro',
            en: 'Green bamboo color',
            rgb: '0,100,66',
            hex: '#006442',
          },
          {
            name: '利休鼠',
            romanized: 'Rikyūnezumi',
            en: 'Greyish dark green',
            rgb: '101,98,85',
            hex: '#656255',
          },
          {
            name: 'びろうど',
            romanized: 'Birōdo',
            en: 'Velvet',
            rgb: '34,70,52',
            hex: '#224634',
          },
          {
            name: '虫襖',
            romanized: "Mushi'ao",
            en: 'Insect screen',
            rgb: '45,68,54',
            hex: '#2D4436',
          },
          {
            name: '藍海松茶',
            romanized: 'Aimirucha',
            en: 'Indigo Codium fragile seaweed brown',
            rgb: '46,55,46',
            hex: '#2E372E',
          },
          {
            name: '沈香茶',
            romanized: 'Tonocha',
            en: 'Aloeswood brown',
            rgb: '90,100,87',
            hex: '#5A6457',
          },
          {
            name: '水浅葱',
            romanized: "Mizu'asagi",
            en: 'Pale green onion',
            rgb: '116,159,141',
            hex: '#749F8D',
          },
          {
            name: '青磁色',
            romanized: 'Seiji-iro',
            en: 'Celadon color',
            rgb: '129,156,139',
            hex: '#819C8B',
          },
          {
            name: '青碧',
            romanized: 'Seiheki',
            en: 'Blue-green',
            rgb: '58,105,96',
            hex: '#3A6960',
          },
          {
            name: '錆鉄御納戸',
            romanized: 'Sabitetsuonando',
            en: 'Rusty storeroom',
            rgb: '58,64,59',
            hex: '#3A403B',
          },
          {
            name: '鉄色',
            romanized: 'Tetsu-iro',
            en: 'Iron color',
            rgb: '43,55,51',
            hex: '#2B3733',
          },
          {
            name: '御召茶',
            romanized: 'Omeshicha',
            en: 'Silk crepe brown',
            rgb: '53,78,75',
            hex: '#354E4B',
          },
          {
            name: '高麗納戸',
            romanized: 'Kōrainando',
            en: 'Goryeo storeroom',
            rgb: '32,56,56',
            hex: '#203838',
          },
        ],
      },
      {
        series: 'Blue/blue violet series',
        data: [
          {
            name: '湊鼠',
            romanized: 'Minatonezumi',
            en: 'Harbor rat',
            rgb: '117,125,117',
            hex: '#757D75',
          },
          {
            name: '青鈍',
            romanized: 'Aonibi',
            en: 'Dull blue',
            rgb: '79,73,68',
            hex: '#4F4944',
          },
          {
            name: '鉄御納戸',
            romanized: 'Tetsuonando',
            en: 'Iron storage',
            rgb: '43,55,54',
            hex: '#2B3736',
          },
          {
            name: '水色',
            romanized: 'Mizu-iro',
            en: 'Aqua Blue color',
            rgb: '134,171,165',
            hex: '#86ABA5',
          },
          {
            name: '錆浅葱',
            romanized: "Sabi'asagi",
            en: 'Rusted light-blue',
            rgb: '106,127,122',
            hex: '#6A7F7A',
          },
          {
            name: '瓶覗',
            romanized: 'Kamenozoki',
            en: 'Inside of a bottle',
            rgb: '198,194,182',
            hex: '#C6C2B6',
          },
          {
            name: '浅葱色',
            romanized: 'Asagi-iro',
            en: 'Light blue color',
            rgb: '72,146,155',
            hex: '#48929B',
          },
          {
            name: '新橋色',
            romanized: 'Shinbashi-iro',
            en: '"New Bridge" color',
            rgb: '0,108,127',
            hex: '#006C7F',
          },
          {
            name: '錆御納戸',
            romanized: "Sabi'onando",
            en: 'Rusty storage',
            rgb: '69,88,89',
            hex: '#455859',
          },
          {
            name: '藍鼠',
            romanized: 'Ainezumi',
            en: 'Mousy indigo',
            rgb: '92,84,78',
            hex: '#5C544E',
          },
          {
            name: '藍色',
            romanized: 'Ai-iro',
            en: 'Indigo color',
            rgb: '38,67,72',
            hex: '#264348',
          },
          {
            name: '御納戸色',
            romanized: 'Onando-iro',
            en: 'Onando color',
            rgb: '54,65,65',
            hex: '#364141',
          },
          {
            name: '花浅葱',
            romanized: "Hana'asagi",
            en: 'Light blue flower',
            rgb: '29,105,124',
            hex: '#1D697C',
          },
          {
            name: '千草色',
            romanized: 'Chigusa-iro',
            en: 'Thousand herb color',
            rgb: '49,117,137',
            hex: '#317589',
          },
          {
            name: '舛花色',
            romanized: 'Masuhana-iro',
            en: 'Opposite flower color',
            rgb: '77,100,108',
            hex: '#4D646C',
          },
          {
            name: '縹',
            romanized: 'Hanada',
            en: 'Light blue silk',
            rgb: '4,79,103',
            hex: '#044F67',
          },
          {
            name: '熨斗目花色',
            romanized: 'Noshimehana-iro',
            en: 'Iron head flower color',
            rgb: '52,77,86',
            hex: '#344D56',
          },
          {
            name: '御召御納戸',
            romanized: "Omeshi'onando",
            en: 'Kimono storage',
            rgb: '61,76,81',
            hex: '#3D4C51',
          },
          {
            name: '空色',
            romanized: 'Sora-iro',
            en: 'Sky Blue color',
            rgb: '77,143,172',
            hex: '#4D8FAC',
          },
          {
            name: '黒橡',
            romanized: 'Kurotsurubami',
            en: 'Black chestnut oak',
            rgb: '37,35,33',
            hex: '#252321',
          },
          {
            name: '群青色',
            romanized: 'Gunjō-iro',
            en: 'Ultramarine color',
            rgb: '93,140,174',
            hex: '#5D8CAE',
          },
          {
            name: '紺',
            romanized: 'Kon',
            en: 'Dark blue',
            rgb: '25,34,54',
            hex: '#192236',
          },
          {
            name: '褐色',
            romanized: 'Kachi-iro',
            en: 'Coarse wool color',
            rgb: '24,27,38',
            hex: '#181B26',
          },
          {
            name: '瑠璃色',
            romanized: 'Ruri-iro',
            en: 'Lapis lazuli color',
            rgb: '31,71,136',
            hex: '#1F4788',
          },
          {
            name: '紺青色',
            romanized: 'Konjō-iro',
            en: 'Prussian blue color',
            rgb: '0,49,113',
            hex: '#003171',
          },
          {
            name: '瑠璃紺',
            romanized: 'Rurikon',
            en: 'Dark blue lapis lazuli',
            rgb: '27,41,75',
            hex: '#1B294B',
          },
          {
            name: '紅碧',
            romanized: 'Benimidori',
            en: 'Stained red',
            rgb: '120,119,155',
            hex: '#78779B',
          },
          {
            name: '紺桔梗',
            romanized: 'Konkikyō',
            en: 'Navy blue bellflower',
            rgb: '25,31,69',
            hex: '#191F45',
          },
          {
            name: '藤鼠',
            romanized: 'Fujinezumi',
            en: 'Mousy wisteria',
            rgb: '118,105,128',
            hex: '#766980',
          },
          {
            name: '紅掛花色',
            romanized: 'Benikakehana-iro',
            en: 'Safflower color',
            rgb: '90,79,116',
            hex: '#5A4F74',
          },
          {
            name: '藤色',
            romanized: 'Fuji-iro',
            en: 'Wisteria color',
            rgb: '137,114,158',
            hex: '#89729E',
          },
          {
            name: '二藍',
            romanized: "Futa'ai",
            en: 'Dark indigo',
            rgb: '97,78,110',
            hex: '#614E6E',
          },
        ],
      },
      {
        series: 'Violet series',
        data: [
          {
            name: '藤紫',
            romanized: 'Fujimurasaki',
            en: 'Wisteria purple',
            rgb: '135,95,154',
            hex: '#875F9A',
          },
          {
            name: '桔梗色',
            romanized: 'Kikyō-iro',
            en: 'Bellflower color',
            rgb: '93,63,106',
            hex: '#5D3F6A',
          },
          {
            name: '紫苑色',
            romanized: "Shi'on-iro",
            en: 'Tatarian aster color',
            rgb: '151,110,154',
            hex: '#976E9A',
          },
          {
            name: '滅紫',
            romanized: 'Messhi',
            en: 'Disappearing purple',
            rgb: '63,49,58',
            hex: '#3F313A',
          },
          {
            name: '紫紺',
            romanized: 'Shikon',
            en: 'Blue-violet',
            rgb: '43,32,40',
            hex: '#2B2028',
          },
          {
            name: '深紫',
            romanized: 'Kokimurasaki',
            en: 'Deep purple',
            rgb: '58,36,59',
            hex: '#3A243B',
          },
          {
            name: '薄色',
            romanized: 'Usu-iro',
            en: 'Thin color',
            rgb: '168,124,160',
            hex: '#A87CA0',
          },
          {
            name: '半色',
            romanized: 'Hashita-iro',
            en: 'Half color',
            rgb: '141,96,140',
            hex: '#8D608C',
          },
          {
            name: '菫色',
            romanized: 'Sumire-iro',
            en: 'Violet color',
            rgb: '91,50,86',
            hex: '#5B3256',
          },
          {
            name: '紫',
            romanized: 'Murasaki',
            en: 'Purple',
            rgb: '79,40,75',
            hex: '#4F284B',
          },
          {
            name: '黒紅',
            romanized: 'Kurobeni',
            en: 'Dark red',
            rgb: '35,25,30',
            hex: '#23191E',
          },
          {
            name: '菖蒲色',
            romanized: 'Ayame-iro',
            en: 'Iris color',
            rgb: '118,53,104',
            hex: '#763568',
          },
          {
            name: '紅藤',
            romanized: 'Benifuji',
            en: 'Red wisteria',
            rgb: '187,119,150',
            hex: '#BB7796',
          },
          {
            name: '杜若',
            romanized: 'Kakitsubata',
            en: 'Rabbit-ear iris',
            rgb: '73,30,60',
            hex: '#491E3C',
          },
          {
            name: '鳩羽鼠',
            romanized: 'Hatobanezumi',
            en: 'Dove feather grey',
            rgb: '117,93,91',
            hex: '#755D5B',
          },
          {
            name: '葡萄鼠',
            romanized: 'Budōnezumi',
            en: 'Grape mouse',
            rgb: '99,66,75',
            hex: '#63424B',
          },
          {
            name: '蒲萄',
            romanized: 'Ebizome',
            en: 'Vine grape',
            rgb: '109,43,80',
            hex: '#6D2B50',
          },
          {
            name: '藤煤竹',
            romanized: 'Fujisusutake',
            en: 'Wisteria and burnt-bamboo',
            rgb: '77,59,60',
            hex: '#4D3B3C',
          },
          {
            name: '牡丹',
            romanized: 'Bōtan',
            en: 'Tree peony',
            rgb: '164,52,93',
            hex: '#A4345D',
          },
          {
            name: '梅紫',
            romanized: 'Umemurasaki',
            en: 'Plum purple',
            rgb: '143,65,85',
            hex: '#8F4155',
          },
          {
            name: '似せ紫',
            romanized: 'Nisemurasaki',
            en: 'Fake purple',
            rgb: '67,36,42',
            hex: '#43242A',
          },
          {
            name: '紫鳶',
            romanized: 'Murasakitobi',
            en: 'Purple kite',
            rgb: '81,44,49',
            hex: '#512C31',
          },
          {
            name: '蘇芳',
            romanized: "Su'ō",
            en: 'Sappanwood',
            rgb: '126,38,57',
            hex: '#7E2639',
          },
          {
            name: '桑染',
            romanized: 'Kuwazome',
            en: 'Mulberry dye',
            rgb: '89,41,44',
            hex: '#59292C',
          },
          {
            name: '紅消鼠',
            romanized: 'Benikeshinezumi',
            en: 'Vanishing red mouse',
            rgb: '68,49,46',
            hex: '#44312E',
          },
        ],
      },
      {
        series: 'Achromatic series',
        data: [
          {
            name: '白練',
            romanized: 'Shironeri',
            en: 'Unbleached silk',
            rgb: '255,221,202',
            hex: '#FFDDCA',
          },
          {
            name: '白鼠',
            romanized: 'Shironezumi',
            en: 'White mouse',
            rgb: '185,161,147',
            hex: '#B9A193',
          },
          {
            name: '銀鼠',
            romanized: 'Ginnezumi',
            en: 'Silver-grey',
            rgb: '151,134,124',
            hex: '#97867C',
          },
          {
            name: '素鼠',
            romanized: 'Sunezumi',
            en: 'Plain mouse',
            rgb: '110,95,87',
            hex: '#6E5F57',
          },
          {
            name: '丼鼠',
            romanized: 'Dobunezumi',
            en: 'Brown rat grey',
            rgb: '75,60,57',
            hex: '#4B3C39',
          },
          {
            name: '藍墨茶',
            romanized: 'Aisumicha',
            en: 'Indigo ink brown',
            rgb: '57,52,50',
            hex: '#393432',
          },
          {
            name: '檳榔子染',
            romanized: 'Binrōjizome',
            en: 'Betel nut-dyed',
            rgb: '53,41,37',
            hex: '#352925',
          },
          {
            name: '墨色',
            romanized: 'Sumi-iro',
            en: 'Ink color',
            rgb: '39,34,31',
            hex: '#27221F',
          },
          {
            name: '黒色',
            romanized: 'Kokushoku',
            en: 'Black',
            rgb: '23,20,18',
            hex: '#171412',
          },
          {
            name: '藍白',
            romanized: 'Aijiro',
            en: 'Indigo white',
            rgb: '235, 246, 247',
            hex: '#EBF6F7',
          },
        ],
      },
    ]);

    function pickColor(e: MouseEvent) {
      const target = e.target;
      let value: string | undefined;
      if (
        navigator.clipboard &&
        target instanceof HTMLTableCellElement &&
        (value = target.dataset['value'])
      ) {
        navigator.clipboard.writeText(value).then(() => {
          BugMessage.info(
            '<strong>' + value + '</strong> <i>copied</i>',
            true
          );
        });
      }
    }

    return { list, pickColor };
  },
});
</script>

<style lang="scss" scoped>
.color-table {
  width: 100%;
  margin: 15px 0 25px 0;
  background: #f8f9fa;

  thead {
    background: #eaecf0;
  }

  th,
  td {
    border: 1px solid #a2a9b1;
    padding: 8px 10px;
  }
}
</style>
